ARG FEDORA_MAJOR_VERSION=44
ARG AKMODS_NVIDIA_IMAGE=ghcr.io/ublue-os/akmods-nvidia-open:main-${FEDORA_MAJOR_VERSION}
ARG BASE_IMAGE=ghcr.io/ublue-os/base-main:latest

FROM ${AKMODS_NVIDIA_IMAGE} AS akmods_nvidia

FROM ${BASE_IMAGE}

COPY scripts/ /tmp/scripts/
COPY system_files/desktop/ /

RUN /tmp/scripts/base.sh
RUN /tmp/scripts/niri.sh
RUN --mount=type=bind,from=akmods_nvidia,src=/rpms,dst=/tmp/akmods-nv-rpms \
    /tmp/scripts/nvidia.sh

RUN bootc container lint
