ARG FEDORA_MAJOR_VERSION=44
ARG BASE_IMAGE=quay.io/fedora/fedora-bootc:${FEDORA_MAJOR_VERSION}

FROM ${BASE_IMAGE}

COPY scripts/ /tmp/scripts/
COPY system_files/server/ /

RUN /tmp/scripts/base.sh

RUN bootc container lint
