ARG FEDORA_MAJOR_VERSION=44
ARG BASE_IMAGE=ghcr.io/ublue-os/base-main:latest

FROM ${BASE_IMAGE}

COPY scripts/ /tmp/scripts/
COPY system_files/laptop/ /

RUN /tmp/scripts/base.sh
RUN /tmp/scripts/niri.sh

RUN bootc container lint
