#!/bin/sh
set -euo pipefail

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=niri
export XDG_CURRENT_DESKTOP=niri
export GTK_THEME=Adwaita:dark
export QT_QPA_PLATFORMTHEME=gtk3
export MOZ_ENABLE_WAYLAND=1

exec niri
